var sourcesIndex = {};
sourcesIndex["nodle_parachain"] = {"name":"","files":["chain_spec.rs","cli.rs","command.rs","executor.rs","main.rs","rpc.rs","service.rs"]};
sourcesIndex["pallet_allocations"] = {"name":"","files":["lib.rs","migrations.rs","weights.rs"]};
sourcesIndex["pallet_grants"] = {"name":"","files":["lib.rs","migrations.rs","weights.rs"]};
sourcesIndex["pallet_mandate"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_poa"] = {"name":"","files":["lib.rs","migrations.rs"]};
sourcesIndex["pallet_reserve"] = {"name":"","files":["lib.rs","weights.rs"]};
sourcesIndex["pallet_staking"] = {"name":"","files":["hooks.rs","lib.rs","migrations.rs","set.rs","slashing.rs","types.rs","weights.rs"]};
sourcesIndex["primitives"] = {"name":"","files":["lib.rs"]};
sourcesIndex["runtime_eden"] = {"name":"","files":["constants.rs","implementations.rs","lib.rs","pallets_consensus.rs","pallets_governance.rs","pallets_nodle.rs","pallets_parachain.rs","pallets_system.rs","pallets_util.rs","version.rs"]};
sourcesIndex["support"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
