/*
 * This file is part of the Nodle Chain distributed at https://github.com/NodleCode/chain
 * Copyright (C) 2020-2024  Nodle International
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//! Autogenerated weights for pallet_multisig
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-08-14, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `chain-bench-a18ada46`, CPU: `AMD EPYC 7B13`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./target/release/nodle-parachain
// benchmark
// pallet
// --pallet=pallet_multisig
// --extrinsic=*
// --steps=50
// --repeat=20
// --genesis-builder=runtime
// --runtime=./target/release/wbuild/runtime-eden/runtime_eden.wasm
// --wasm-execution=compiled
// --template=./.maintain/external_pallet_weights.hbs
// --output=runtimes/eden/src/weights

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

/// Weight functions for `pallet_multisig`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_multisig::WeightInfo for WeightInfo<T> {
	/// The range of component `z` is `[0, 10000]`.
	fn as_multi_threshold_1(z: u32) -> Weight {
		// Minimum execution time: 14_570 nanoseconds.
		Weight::from_parts(15_295_606_u64, 0)
			// Standard Error: 3
			.saturating_add(Weight::from_parts(431_u64, 0).saturating_mul(z as u64))
	}
	// Storage: `Multisig::Multisigs` (r:1 w:1)
	// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3346), added: 5821, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[2, 100]`.
	/// The range of component `z` is `[0, 10000]`.
	fn as_multi_create(s: u32, z: u32) -> Weight {
		// Minimum execution time: 46_760 nanoseconds.
		Weight::from_parts(39_414_515_u64, 0)
			// Standard Error: 1_094
			.saturating_add(Weight::from_parts(93_881_u64, 0).saturating_mul(s as u64))
			// Standard Error: 10
			.saturating_add(Weight::from_parts(1_399_u64, 0).saturating_mul(z as u64))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: `Multisig::Multisigs` (r:1 w:1)
	// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3346), added: 5821, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[3, 100]`.
	/// The range of component `z` is `[0, 10000]`.
	fn as_multi_approve(s: u32, z: u32) -> Weight {
		// Minimum execution time: 27_060 nanoseconds.
		Weight::from_parts(19_497_274_u64, 0)
			// Standard Error: 685
			.saturating_add(Weight::from_parts(88_426_u64, 0).saturating_mul(s as u64))
			// Standard Error: 6
			.saturating_add(Weight::from_parts(1_423_u64, 0).saturating_mul(z as u64))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: `Multisig::Multisigs` (r:1 w:1)
	// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3346), added: 5821, mode: `MaxEncodedLen`)
	// Storage: `System::Account` (r:1 w:1)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[2, 100]`.
	/// The range of component `z` is `[0, 10000]`.
	fn as_multi_complete(s: u32, z: u32) -> Weight {
		// Minimum execution time: 50_470 nanoseconds.
		Weight::from_parts(40_414_877_u64, 0)
			// Standard Error: 1_156
			.saturating_add(Weight::from_parts(121_143_u64, 0).saturating_mul(s as u64))
			// Standard Error: 11
			.saturating_add(Weight::from_parts(1_496_u64, 0).saturating_mul(z as u64))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	// Storage: `Multisig::Multisigs` (r:1 w:1)
	// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3346), added: 5821, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[2, 100]`.
	fn approve_as_multi_create(s: u32) -> Weight {
		// Minimum execution time: 34_290 nanoseconds.
		Weight::from_parts(37_241_931_u64, 0)
			// Standard Error: 1_256
			.saturating_add(Weight::from_parts(98_350_u64, 0).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: `Multisig::Multisigs` (r:1 w:1)
	// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3346), added: 5821, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[2, 100]`.
	fn approve_as_multi_approve(s: u32) -> Weight {
		// Minimum execution time: 16_450 nanoseconds.
		Weight::from_parts(17_599_041_u64, 0)
			// Standard Error: 767
			.saturating_add(Weight::from_parts(95_942_u64, 0).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// Storage: `Multisig::Multisigs` (r:1 w:1)
	// Proof: `Multisig::Multisigs` (`max_values`: None, `max_size`: Some(3346), added: 5821, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[2, 100]`.
	fn cancel_as_multi(s: u32) -> Weight {
		// Minimum execution time: 33_589 nanoseconds.
		Weight::from_parts(36_245_216_u64, 0)
			// Standard Error: 1_217
			.saturating_add(Weight::from_parts(97_684_u64, 0).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}
